### ISSUE TITLE
ライセンス表記

### ISSUE THREAD

**Issue by mizunashi-mana** [myuon/ghc-compiler-notes#19]
ライセンス表記を docs/index.rst.に記載しておいた方が良いかもしれません。

* GHCのソースからの抽出物であること
* 抽出物は、 The Glasgow Haskell Compiler License 下にあること

の2点は明記しておいた方が無難だと思います

参考: https://gitlab.haskell.org/ghc/ghc/blob/master/LICENSE

**Comment by myuon** [comment]
確かにそうですね
ありがとうございます、明記しておきます
