### ISSUE TITLE
Prevent (possible) infinite loop in workflows

### ISSUE THREAD

**Issue by myuon** [myuon/ghc-compiler-notes#23]
I don't want to be arrested

**Comment by myuon** [comment]
One idea: push generated docs to `release` branch. Updating `master` branch triggers merge to `release` every time. Also prohibiting to push `docs/notes` to `master` (avoid conflicting).

**Comment by mizunashi-mana** [comment]
I agree with pushing `release` branch.

And, I suggest `docs/notes` are removed from `master` .
These were noisy when I tested my patches:
* If formatting algorithm is changed by the patch
* If some notes are changed in latest GHC

**Comment by myuon** [comment]
Done.

- Build docs in `docs` branch.
- Ignore `docs/notes` in `master` branch.
